name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PSPDEV_TAG=ghcr.io/pspdev/pspdev:v20260201" >> $GITHUB_ENV

    - name: Install packages
      run: |
        sudo apt update; sudo apt install -y g++-mingw-w64 gcc-mingw-w64

    - name: Build
      run: |
        bash build.sh

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: beammp_launcher_wine_shim_${{ env.sha_name }}
        path: |
           MinHook.x64.dll
           wintrust.dll
        if-no-files-found: error
